export const DRAG_CONSTRUCTOR_ELEMENT: "DRAG_CONSTRUCTOR_ELEMENT" = "DRAG_CONSTRUCTOR_ELEMENT";
export const DROP_CONSTRUCTOR_ELEMENT: "DROP_CONSTRUCTOR_ELEMENT" = "DROP_CONSTRUCTOR_ELEMENT";
export const DELITE_ELEMENT: "DELITE_ELEMENT" = "DELITE_ELEMENT";
export const DROP_MOVED_ELEMENT: "DROP_MOVED_ELEMENT" = "DROP_MOVED_ELEMENT";
export const CHECK_DROPED_ELEMENT: "CHECK_DROPED_ELEMENT" = "CHECK_DROPED_ELEMENT";
export const CLEAN_CONSTRUCTOR: "CLEAN_CONSTRUCTOR" = "CLEAN_CONSTRUCTOR";

export const GET_MODAL_INGREDIENTS: 'GET_MODAL_INGREDIENTS' = 'GET_MODAL_INGREDIENTS';
export const CLOSE_ING_MODAL: 'CLOSE_ING_MODAL' = 'CLOSE_ING_MODAL';
export const OPEN_ING_MODAL: 'OPEN_ING_MODAL' = 'OPEN_ING_MODAL';
export const DELITE_MODAL_INGREDIENTS: 'DELITE_MODAL_INGREDIENTS' = 'DELITE_MODAL_INGREDIENTS'

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST"; 
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
export const CHANGE_INGREDIENTS_COUNT: "CHANGE_INGREDIENTS_COUNT" = "CHANGE_INGREDIENTS_COUNT";

export const OPEN_ORDER_MODAL: "OPEN_ORDER_MODAL" = "OPEN_ORDER_MODAL";
export const CLOSE_ORDER_MODAL: "CLOSE_ORDER_MODAL" = "CLOSE_ORDER_MODAL";
export const GET_ORDER_NUMBER_REQUEST: "GET_ORDER_NUMBER_REQUEST" = "GET_ORDER_NUMBER_REQUEST";
export const GET_ORDER_NUMBER_SUCCESS: "GET_ORDER_NUMBER_SUCCESS" = "GET_ORDER_NUMBER_SUCCESS";
export const ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS" = "ADD_ORDER_SUCCESS";
export const CLEAN_ORDER: "CLEAN_ORDER" = "CLEAN_ORDER";

export const ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST" = "ADD_ORDER_REQUEST";
export const ADD_ORDER_FAILED: "ADD_ORDER_FAILED" = "ADD_ORDER_FAILED";
export const RESET_ORDER_DATA: "RESET_ORDER_DATA" = "RESET_ORDER_DATA";

export const SEND_EMAIL_REQUEST: "SEND_EMAIL_REQUEST" = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS: "SEND_EMAIL_SUCCESS" = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILED: "SEND_EMAIL_FAILED" = "SEND_EMAIL_FAILED";
export const SEND_NEW_PASSWORD_REQUEST: "SEND_NEW_PASSWORD_REQUEST" = "SEND_NEW_PASSWORD_REQUEST";
export const SEND_NEW_PASSWORD_SUCCESS: "SEND_NEW_PASSWORD_SUCCESS" = "SEND_NEW_PASSWORD_SUCCESS";
export const SEND_NEW_PASSWORD_FAILED: "SEND_NEW_PASSWORD_FAILED" = "SEND_NEW_PASSWORD_FAILED";
export const SEND_NEW_USER_REQUEST: "SEND_NEW_USER_REQUEST" = "SEND_NEW_USER_REQUEST";
export const SEND_NEW_USER_SUCCESS: "SEND_NEW_USER_SUCCESS" = "SEND_NEW_USER_SUCCESS";
export const SEND_NEW_USER_FAILED: "SEND_NEW_USER_FAILED" = "SEND_NEW_USER_FAILED";
export const LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST" = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS" = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED: "LOGIN_USER_FAILED" = "LOGIN_USER_FAILED";
export const USER_REQUEST: 'USER_REQUEST' = 'USER_REQUEST';
export const USER_SUCCESS: 'USER_SUCCESS' = 'USER_SUCCESS';
export const USER_FAILED: 'USER_FAILED' = 'USER_FAILED';
export const AUTH_CHECKED: 'AUTH_CHECKED' = 'AUTH_CHECKED';
export const SEND_NEW_DATA: 'SEND_NEW_DATA' = 'SEND_NEW_DATA';
export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';
export const RESET_USERS_DATA: 'RESET_USERS_DATA' = 'RESET_USERS_DATA';
export const VISITED_FORGOT_PASSWORD: 'VISITED_FORGOT_PASSWORD' = 'VISITED_FORGOT_PASSWORD';